#!/usr/bin/env python3
"""FORGE render-spec-index (Spec 254 — Approach D).

Renders the spec index view (docs/specs/README.md) from per-spec frontmatter.
The spec index is purely derivable from `Status:` fields across spec files.

Usage:
    python3 .forge/lib/render_spec_index.py [--specs-dir docs/specs] [--output -]

Determinism: byte-identical output across two consecutive invocations against
the same input state (Spec 254 AC 14 substitute).
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

_LIB_DIR = Path(__file__).resolve().parent
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

# Force UTF-8 on stdout/stderr.
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except (AttributeError, OSError):
    pass

from spec_frontmatter import iter_spec_files, parse_spec_file  # noqa: E402


def render(specs_dir: Path, *, header: bool = True) -> str:
    files = iter_spec_files(specs_dir)
    rows: list[tuple[str, str, str]] = []
    for f in files:
        fm = parse_spec_file(f)
        if fm is None:
            continue
        spec_id = fm.get("spec_id", "")
        slug = f.stem  # e.g., "390-jinja-force-preserve"
        status = (fm.get("status") or "?").strip()
        if not spec_id:
            continue
        rows.append((spec_id, slug, status))

    rows.sort(key=lambda r: r[0])

    lines: list[str] = []
    if header:
        lines.append("# Specs Index")
        lines.append("")
        lines.append("<!--")
        lines.append(
            "  DO NOT EDIT — generated by render_spec_index.py (Spec 254 — Approach D)."
        )
        lines.append("  Source: per-spec frontmatter under docs/specs/NNN-*.md")
        lines.append(
            f"  Rendered: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
        )
        lines.append("-->")
        lines.append("")
        lines.append("All specs in this project, sorted by ID. The `Status:` field in each spec file is authoritative.")
        lines.append("")

    for spec_id, slug, status in rows:
        lines.append(f"- [{slug}](./{slug}.md) - status: {status}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render FORGE spec-index from frontmatter")
    p.add_argument("--specs-dir", default="docs/specs")
    p.add_argument("--output", default="-")
    p.add_argument("--no-header", action="store_true")
    args = p.parse_args(argv)

    out = render(Path(args.specs_dir), header=not args.no_header)
    if args.output == "-":
        sys.stdout.write(out)
    else:
        Path(args.output).write_text(out, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
