#!/usr/bin/env python3
"""FORGE render-changelog (Spec 254 — Approach D).

Renders the spec changelog view chronologically (newest-first) from per-spec
event streams (`.forge/state/events/<spec-id>/*.jsonl`).

Falls back to spec frontmatter `Closed:`/`Status:` fields when no event streams
exist (greenfield projects, pre-migration state).

Usage:
    python3 .forge/lib/render_changelog.py [--specs-dir docs/specs] \
                                            [--events-dir .forge/state/events] \
                                            [--output -]

Determinism: byte-identical output across two consecutive invocations against
the same input state (Spec 254 AC 14 substitute).
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

_LIB_DIR = Path(__file__).resolve().parent
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

# Force UTF-8 on stdout/stderr — Windows cp1252 default chokes on `→` `−` etc.
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except (AttributeError, OSError):
    pass

from events import load_events  # noqa: E402
from spec_frontmatter import iter_spec_files, parse_spec_file  # noqa: E402

# Event types to surface in the changelog (chronological-history-relevant)
CHANGELOG_EVENT_TYPES = {
    "spec-started",
    "spec-approved",
    "spec-implemented",
    "spec-closed",
    "spec-deferred",
    "spec-deprecated",
    "revise",
}


def render(specs_dir: Path, events_dir: Path, *, header: bool = True) -> str:
    # Build spec_id → title map for joins
    title_by_id: dict[str, str] = {}
    for f in iter_spec_files(specs_dir):
        fm = parse_spec_file(f)
        if fm is None:
            continue
        sid = str(fm.get("spec_id", ""))
        if sid:
            title_by_id[sid] = fm.get("title", "")

    # Load all events
    all_events = load_events(base_dir=events_dir)

    # Build entries: (timestamp, spec_id, event_type, line)
    entries: list[tuple[str, str, str, str]] = []
    for ev in all_events:
        et = ev.get("event_type", "")
        if et not in CHANGELOG_EVENT_TYPES:
            continue
        spec_id = ev.get("_spec_id", "?")
        ts = ev.get("timestamp", "")
        title = title_by_id.get(spec_id, "")
        msg = ev.get("payload", {}).get("message", "")
        date = ts.split("T", 1)[0] if "T" in ts else ts

        verb = {
            "spec-started": "started",
            "spec-approved": "approved",
            "spec-implemented": "implemented",
            "spec-closed": "closed",
            "spec-deferred": "deferred",
            "spec-deprecated": "deprecated",
            "revise": "revised",
        }.get(et, et)

        line = f"- {date}: Spec {spec_id} {verb}"
        if title:
            line += f" — {title}"
        if msg:
            line += f" ({msg})"
        line += "."
        entries.append((ts, spec_id, et, line))

    # Sort chronologically newest-first; tiebreak by spec_id then event_type
    entries.sort(key=lambda x: (x[0], x[1], x[2]), reverse=True)

    lines: list[str] = []
    if header:
        lines.append("# Specs Changelog")
        lines.append("")
        lines.append("<!--")
        lines.append(
            "  DO NOT EDIT — generated by render_changelog.py (Spec 254 — Approach D)."
        )
        lines.append(
            "  Source: per-spec event streams under .forge/state/events/<spec-id>/"
        )
        lines.append(
            f"  Rendered: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}"
        )
        lines.append("-->")
        lines.append("")
        lines.append("## Entries")
        lines.append("")

    if not entries:
        lines.append("_No events recorded yet. Lifecycle commands (/implement, /close, /revise) populate event streams._")
    else:
        for _, _, _, line in entries:
            lines.append(line)

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render FORGE changelog from event streams")
    p.add_argument("--specs-dir", default="docs/specs")
    p.add_argument("--events-dir", default=".forge/state/events")
    p.add_argument("--output", default="-")
    p.add_argument("--no-header", action="store_true")
    args = p.parse_args(argv)

    out = render(
        Path(args.specs_dir),
        Path(args.events_dir),
        header=not args.no_header,
    )
    if args.output == "-":
        sys.stdout.write(out)
    else:
        Path(args.output).write_text(out, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
