#!/usr/bin/env python3
"""FORGE render-backlog (Spec 254 — Approach D).

Renders the ranked backlog view from per-spec frontmatter sources.
No reads against docs/backlog.md — the canonical source is each spec file's
frontmatter (`docs/specs/NNN-*.md`).

Usage:
    python3 .forge/lib/render_backlog.py [--specs-dir docs/specs] [--output -]

Default writes to stdout.

Determinism: output is byte-identical for the same input state across two
consecutive invocations (Spec 254 AC 14 — unified-Python deterministic-output
substitute for bash+PS parity gate).
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

# Force UTF-8 on stdout/stderr — Windows cp1252 default chokes on `→` `−` etc.
# (Spec 254 implementation note; same workaround as strategic-scope.py)
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except (AttributeError, OSError):
    pass

# Add .forge/lib to path when invoked directly
_LIB_DIR = Path(__file__).resolve().parent
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

from spec_frontmatter import iter_spec_files, parse_spec_file  # noqa: E402

STATUS_MARKER = {
    "closed": "✅",
    "deprecated": "⊘",
    "deferred": "⏸",
    "in-progress": "→",
    "implemented": "→",
    "draft": None,  # numeric rank assigned by score
    "approved": None,
}


def _status_norm(s: str) -> str:
    return (s or "").strip().lower()


def render(specs_dir: Path, *, header: bool = True) -> str:
    files = iter_spec_files(specs_dir)
    rows = []
    for f in files:
        fm = parse_spec_file(f)
        if fm is None:
            continue
        rows.append(fm)

    # Partition by status
    by_status: dict[str, list[dict]] = {}
    for r in rows:
        st = _status_norm(r.get("status", ""))
        by_status.setdefault(st, []).append(r)

    # Sort drafts by score desc; assign numeric ranks
    drafts = sorted(
        by_status.get("draft", []),
        key=lambda r: (-(r.get("score") or 0), r.get("spec_id", "")),
    )

    lines: list[str] = []
    if header:
        lines.append("# Spec Backlog — FORGE")
        lines.append("")
        lines.append("<!--")
        lines.append("  DO NOT EDIT — generated by render_backlog.py (Spec 254 — Approach D).")
        lines.append("  Source: per-spec frontmatter under docs/specs/NNN-*.md")
        lines.append(f"  Rendered: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
        lines.append("-->")
        lines.append("")
        lines.append(
            "Scored using the [prioritization scoring rubric](process-kit/scoring-rubric.md)."
        )
        lines.append(
            "Formula: `(BV × 3) + ((6−E) × 2) + ((6−R) × 2) + (SR × 1)` — max 40."
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Ranked backlog")
        lines.append("")
        lines.append(
            "| Rank | Spec | Title | BV | E | R | SR | Score | Depends | Status |"
        )
        lines.append(
            "|------|------|-------|----|---|---|----|-------|---------|--------|"
        )

    def emit(rank: str, r: dict) -> str:
        title = (r.get("title") or "").replace("|", "\\|")
        bv = r.get("bv", "")
        e = r.get("e", "")
        rr = r.get("r", "")
        sr = r.get("sr", "")
        score = r.get("score", "")
        deps = (r.get("dependencies") or "—").replace("|", "\\|")
        status = r.get("status", "?")
        spec_id = r.get("spec_id", "?")
        return (
            f"| {rank} | {spec_id} | {title} | {bv} | {e} | {rr} | {sr} | "
            f"**{score}** | {deps} | {status} |"
        )

    # Active rows (in-progress / implemented) first
    for status_key in ("in-progress", "implemented"):
        for r in sorted(by_status.get(status_key, []), key=lambda x: x.get("spec_id", "")):
            lines.append(emit(STATUS_MARKER[status_key], r))

    # Numbered drafts (sorted by score desc, then by spec_id)
    for idx, r in enumerate(drafts, 1):
        lines.append(emit(str(idx), r))

    # Deferred drafts (status: deferred — not standard but used for hold patterns)
    for r in sorted(by_status.get("deferred", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["deferred"], r))

    # Closed at bottom
    for r in sorted(by_status.get("closed", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["closed"], r))

    # Deprecated at very bottom
    for r in sorted(by_status.get("deprecated", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["deprecated"], r))

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render FORGE backlog from per-spec frontmatter")
    p.add_argument(
        "--specs-dir",
        default="docs/specs",
        help="Directory containing NNN-*.md spec files (default: docs/specs)",
    )
    p.add_argument(
        "--output",
        default="-",
        help="Output path; '-' for stdout (default: -)",
    )
    p.add_argument(
        "--no-header",
        action="store_true",
        help="Suppress the header + DO-NOT-EDIT comment (table only)",
    )
    args = p.parse_args(argv)

    out = render(Path(args.specs_dir), header=not args.no_header)
    if args.output == "-":
        sys.stdout.write(out)
    else:
        Path(args.output).write_text(out, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
