#!/usr/bin/env python3
"""FORGE render-backlog (Spec 254 — Approach D).

Renders the ranked backlog view from per-spec frontmatter sources.
# forge:path-literal-ok (docstring/prose — classic-default spelling in help text; Spec 575)
No reads against docs/backlog.md — the canonical source is each spec file's
frontmatter (`docs/specs/NNN-*.md`).
# forge:path-literal-ok (comment) — module-docstring prose; actual default resolved below

Usage:
    python3 .forge/lib/render_backlog.py [--specs-dir docs/specs] [--output -]

Default writes to stdout.

Determinism: output is byte-identical for the same input state across two
consecutive invocations (Spec 254 AC 14 — unified-Python deterministic-output
substitute for bash+PS parity gate).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Spec 401: Python 3.10+ floor — defense-in-depth for direct invocation when forge-py wrapper is bypassed.
if sys.version_info < (3, 10):
    sys.stderr.write(f"error: Python 3.10+ required (found {sys.version_info.major}.{sys.version_info.minor})\n")
    sys.exit(1)

# Force UTF-8 on stdout/stderr — Windows cp1252 default chokes on `→` `−` etc.
# (Spec 254 implementation note; same workaround as strategic-scope.py)
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    sys.stderr.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except (AttributeError, OSError):
    pass

# Add .forge/lib to path when invoked directly
_LIB_DIR = Path(__file__).resolve().parent
if str(_LIB_DIR) not in sys.path:
    sys.path.insert(0, str(_LIB_DIR))

from spec_frontmatter import iter_spec_files, parse_spec_file  # noqa: E402
from render_invariant import assert_complete  # noqa: E402

try:
    from runtime_config import resolve_path as _rc_resolve_path  # Spec 564 helper
except ImportError:
    _rc_resolve_path = None


def _default_specs_dir() -> str:
    """Resolve forge.paths.specs via runtime_config; fall back to the classic default."""
    if _rc_resolve_path is not None:
        try:
            value, error = _rc_resolve_path(Path("."), "specs")
            if not error and value:
                return value
        except Exception:
            pass
    return "docs/specs"

STATUS_MARKER = {
    "closed": "✅",
    "deprecated": "⊘",
    "deferred": "⏸",
    "in-progress": "→",
    "implemented": "→",
    "draft": None,  # numeric rank assigned by score
    "approved": None,
}


def _status_norm(s: str) -> str:
    # Spec 493: bucket on the leading lifecycle token. Specs carry an inline
    # reason on terminal states (`deprecated (scope-creep …)`, `deferred (per …)`)
    # — without this, the full string matches no STATUS_MARKER bucket and the
    # row is silently dropped (same drop class as Defect A's comment leak).
    # The corpus only ever uses a space before the parenthetical, so the leading
    # whitespace-delimited token is the canonical status (hyphenated `in-progress`
    # has no internal space, so it is preserved intact).
    return (s or "").strip().lower().split(" ", 1)[0]


def render(specs_dir: Path, *, header: bool = True) -> str:
    files = list(iter_spec_files(specs_dir))
    rows = []
    parse_failures: list[str] = []
    for f in files:
        fm = parse_spec_file(f)
        if fm is None:
            parse_failures.append(f.name)  # Spec 494: a parse failure is a silent drop
            continue
        rows.append(fm)

    # Partition by status
    by_status: dict[str, list[dict]] = {}
    for r in rows:
        st = _status_norm(r.get("status", ""))
        by_status.setdefault(st, []).append(r)

    # Sort the ranked pool (draft + approved) by score desc; assign numeric
    # ranks. Spec 467: the pool previously pulled only "draft", so approved
    # specs vanished despite STATUS_MARKER already mapping "approved".
    drafts = sorted(
        by_status.get("draft", []) + by_status.get("approved", []),
        key=lambda r: (-(r.get("score") or 0), r.get("spec_id", "")),
    )

    lines: list[str] = []
    if header:
        lines.append("# Spec Backlog — FORGE")
        lines.append("")
        lines.append("<!--")
        lines.append("  DO NOT EDIT — generated by render_backlog.py (Spec 254 — Approach D).")
        lines.append(f"  Source: per-spec frontmatter under {specs_dir.as_posix()}/NNN-*.md")
        lines.append("-->")
        lines.append("")
        lines.append(
            "Scored using the [prioritization scoring rubric](process-kit/scoring-rubric.md)."
        )
        lines.append(
            "Formula: `(BV × 3) + ((6−E) × 2) + ((6−R) × 2) + (SR × 1)` — max 40."
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Ranked backlog")
        lines.append("")
        lines.append(
            "| Rank | Spec | Title | BV | E | R | SR | Score | Depends | Status |"
        )
        lines.append(
            "|------|------|-------|----|---|---|----|-------|---------|--------|"
        )

    def emit(rank: str, r: dict) -> str:
        title = (r.get("title") or "").replace("|", "\\|")
        bv = r.get("bv", "")
        e = r.get("e", "")
        rr = r.get("r", "")
        sr = r.get("sr", "")
        score = r.get("score", "")
        deps = (r.get("dependencies") or "—").replace("|", "\\|")
        status = r.get("status", "?")
        spec_id = r.get("spec_id", "?")
        return (
            f"| {rank} | {spec_id} | {title} | {bv} | {e} | {rr} | {sr} | "
            f"**{score}** | {deps} | {status} |"
        )

    # Active rows (in-progress / implemented) first
    for status_key in ("in-progress", "implemented"):
        for r in sorted(by_status.get(status_key, []), key=lambda x: x.get("spec_id", "")):
            lines.append(emit(STATUS_MARKER[status_key], r))

    # Numbered drafts (sorted by score desc, then by spec_id)
    for idx, r in enumerate(drafts, 1):
        lines.append(emit(str(idx), r))

    # Deferred drafts (status: deferred — not standard but used for hold patterns)
    for r in sorted(by_status.get("deferred", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["deferred"], r))

    # Closed at bottom
    for r in sorted(by_status.get("closed", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["closed"], r))

    # Deprecated at very bottom
    for r in sorted(by_status.get("deprecated", []), key=lambda x: x.get("spec_id", "")):
        lines.append(emit(STATUS_MARKER["deprecated"], r))

    # Spec 494: parse-completeness invariant. Every spec file must render exactly
    # one row. A parse failure (fm is None) or a parsed row whose status falls in
    # no emitted bucket is a silent drop (the SIG-493-02 class) — fail loudly and
    # name the dropped IDs rather than emit a short table.
    _EMITTED_BUCKETS = {
        "in-progress", "implemented", "draft", "approved",
        "deferred", "closed", "deprecated",
    }
    unemitted = [
        r.get("spec_id", "?")
        for r in rows
        if _status_norm(r.get("status", "")) not in _EMITTED_BUCKETS
    ]
    emitted_total = len(rows) - len(unemitted)
    assert_complete("render_backlog", len(files), emitted_total, parse_failures + unemitted)

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render FORGE backlog from per-spec frontmatter")
    p.add_argument(
        "--specs-dir",
        default=_default_specs_dir(),
        help="Directory containing NNN-*.md spec files (default: docs/specs)",
    )
    p.add_argument(
        "--output",
        default="-",
        help="Output path; '-' for stdout (default: -)",
    )
    p.add_argument(
        "--no-header",
        action="store_true",
        help="Suppress the header + DO-NOT-EDIT comment (table only)",
    )
    p.add_argument(
        "--mode",
        choices=("stdout", "split-file"),
        default="stdout",
        help="Spec 398: split-file writes to docs/.generated/backlog-table.md "
             "via binary-mode atomic-replace; stdout (default) preserves "
             "Phase 1 stdout behavior.",
    )
    p.add_argument(
        "--split-file-target",
        default="docs/.generated/backlog-table.md",
        help="Target artifact path for --mode=split-file (Spec 398).",
    )
    args = p.parse_args(argv)

    out = render(Path(args.specs_dir), header=not args.no_header)

    if args.mode == "split-file":
        from split_file_writer import write_split_file_artifact
        target = Path(args.split_file_target)
        write_split_file_artifact(target, out)
        return 0

    if args.output == "-":
        sys.stdout.write(out)
    else:
        Path(args.output).write_text(out, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
