"""Shared helper for Spec 398 split-file mode renderer writes.

Binary-mode I/O with explicit newline handling to preserve CRLF/BOM semantics
per Spec 398 Req 3 + DA round-1 critical finding.

All renderers call `write_split_file_artifact(path, text)` to produce a
generated artifact at `path`. Writes via temp file + os.replace for atomicity.
"""

from __future__ import annotations

import os
from pathlib import Path

# Header prepended to every generated artifact (Spec 398 Req 1)
GENERATED_HEADER = (
    "<!-- DO NOT EDIT — generated by .forge/lib/render-*.py — "
    "see docs/process-kit/derived-view-rendering-guide.md -->\n"
)


def _detect_dominant_newline(existing_bytes: bytes) -> bytes:
    """Return b'\\r\\n' if CRLF dominates, else b'\\n'."""
    crlf = existing_bytes.count(b"\r\n")
    lf = existing_bytes.count(b"\n") - crlf
    return b"\r\n" if crlf > lf else b"\n"


def write_split_file_artifact(path: Path, text: str) -> None:
    """Write generated text to `path` via temp+os.replace, binary mode.

    Behavior:
    - Prepends the DO-NOT-EDIT header if not already present in `text`.
    - Encodes UTF-8 (no BOM unless `text` itself includes the BOM marker).
    - Preserves dominant line-ending convention if `path` exists; else uses LF.
    - Ensures exactly one trailing newline (matching dominant convention).
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    # Determine line-ending convention.
    if path.exists():
        try:
            existing = path.read_bytes()
            newline = _detect_dominant_newline(existing)
        except OSError:
            newline = b"\n"
    else:
        newline = b"\n"

    # Ensure header presence.
    if not text.startswith(GENERATED_HEADER.split("\n")[0]):
        text = GENERATED_HEADER + text

    # Encode in LF-only first (text is built with \n), then translate if needed.
    encoded = text.encode("utf-8")

    # Strip trailing newlines, ensure exactly one trailing LF, then translate.
    while encoded.endswith(b"\n"):
        encoded = encoded[:-1]
    encoded += b"\n"

    if newline == b"\r\n":
        # Translate every standalone \n to \r\n; existing \r\n already match.
        # Encoded text is built with \n only, so this is a simple replace.
        encoded = encoded.replace(b"\n", b"\r\n")

    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "wb") as fh:
        fh.write(encoded)
    os.replace(tmp, path)
